name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          # Build the image with both the commit SHA and 'latest' tag
          docker build -t ghcr.io/${{ github.actor }}/whoisapi:${{ github.sha }} \
                       -t ghcr.io/${{ github.actor }}/whoisapi:latest .

      - name: Push Docker image
        run: |
          # Push both the SHA and 'latest' tagged images
          docker push ghcr.io/${{ github.actor }}/whoisapi:${{ github.sha }}
          docker push ghcr.io/${{ github.actor }}/whoisapi:latest

      - name: Set package visibility to public
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GHCR_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"visibility": "public"}' \
            "https://api.github.com/user/packages/container/ghcr.io%2F${{ github.actor }}%2Fwhoisapi%2F${{ github.sha }}/visibility"
